# Generated by Django 5.1.4 on 2024-12-09 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FireIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporter_name', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=255)),
                ('nearby_landmark', models.CharField(max_length=255)),
                ('fire_type', models.CharField(max_length=50)),
                ('fire_severity', models.CharField(max_length=50)),
                ('fire_description', models.TextField()),
            ],
        ),
    ]
