# Generated by Django 5.1.4 on 2025-01-18 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_fireincident_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Citoyen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255, verbose_name='Nom complet')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Adresse e-mail')),
                ('phone', models.CharField(max_length=10, verbose_name='Numéro de téléphone')),
                ('password', models.CharField(max_length=128, verbose_name='Mot de passe')),
            ],
        ),
    ]
