# Generated by Django 5.1.4 on 2025-01-18 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_citoyen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citoyen',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='citoyen',
            name='fullname',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='citoyen',
            name='password',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='citoyen',
            name='phone',
            field=models.CharField(max_length=10),
        ),
    ]
