# Generated by Django 5.1.4 on 2025-01-18 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_citoyen_email_alter_citoyen_fullname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pompier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('numero_tel', models.CharField(max_length=15, verbose_name='Numéro de téléphone')),
                ('equipe', models.CharField(choices=[('incendie', 'Équipe de lutte contre les incendies'), ('secours', 'Équipe de secours et de sauvetage'), ('sauvage', 'Équipe de sauvetage aquatique'), ('médical', 'Équipe de secours médical'), ('montagne', "Équipe d'intervention en milieu montagneux"), ('urgence', 'Équipe de gestion des urgences')], max_length=50, verbose_name='Équipe')),
                ('grade', models.CharField(choices=[('capitaine', 'Capitaine'), ('lieutenant', 'Lieutenant'), ('sergent', 'Sergent'), ('pompier', 'Pompier')], max_length=50, verbose_name='Grade')),
                ('date_recrutement', models.DateField(blank=True, null=True, verbose_name='Date de recrutement')),
                ('en_mission', models.BooleanField(default=False, verbose_name='En mission')),
                ('mission', models.CharField(blank=True, choices=[('incendie_foret', 'Lutte contre les incendies de forêts'), ('incendie_batiment', 'Lutte contre les incendies de bâtiments'), ('incendie_vehicule', 'Lutte contre les incendies de véhicules'), ('secours_urgence', "Secours d'urgence")], max_length=50, null=True, verbose_name='Mission')),
            ],
        ),
        migrations.DeleteModel(
            name='PersonnelPompier',
        ),
        migrations.DeleteModel(
            name='UnitePompier',
        ),
    ]
