# Generated by Django 5.1.4 on 2025-01-18 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_pompier_delete_personnelpompier_delete_unitepompier'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehiculeDePompier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_immatriculation', models.CharField(max_length=20, unique=True)),
                ('type_vehicule', models.CharField(choices=[('Camion-citerne', 'Camion-citerne'), ('Camion-échelle', 'Camion-échelle'), ('Ambulance', 'Ambulance')], max_length=20)),
                ('marque', models.CharField(max_length=50)),
                ('etat', models.CharField(choices=[('Opérationnel', 'Opérationnel'), ('En réparation', 'En réparation')], max_length=20)),
                ('en_service', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Véhicule de pompier',
                'verbose_name_plural': 'Véhicules de pompiers',
            },
        ),
        migrations.DeleteModel(
            name='VehiculePompier',
        ),
    ]
