# Generated by Django 5.1.4 on 2024-12-10 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incendie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('description', models.TextField()),
                ('type', models.CharField(max_length=100)),
                ('severity', models.CharField(max_length=100)),
                ('date_reported', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
