# Generated by Django 5.1.4 on 2024-12-10 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_incendie'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitePompier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name="Nom de l'unité")),
                ('adresse', models.TextField(blank=True, null=True, verbose_name='Adresse')),
                ('telephone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Téléphone')),
            ],
        ),
    ]
