# Generated by Django 5.1.4 on 2024-12-10 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_unitepompier'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehiculePompier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=20, unique=True, verbose_name='Matricule')),
                ('type_vehicule', models.CharField(choices=[('camion', 'Camion'), ('ambulance', 'Ambulance'), ('4x4', '4x4')], max_length=50, verbose_name='Type de véhicule')),
                ('en_service', models.BooleanField(default=True, verbose_name='En service')),
            ],
        ),
    ]
