# Generated by Django 5.1.4 on 2024-12-10 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_vehiculepompier'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonnelPompier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('grade', models.CharField(choices=[('capitaine', 'Capitaine'), ('lieutenant', 'Lieutenant'), ('sergent', 'Sergent'), ('pompier', 'Pompier')], max_length=50, verbose_name='Grade')),
                ('date_recrutement', models.DateField(blank=True, null=True, verbose_name='Date de recrutement')),
            ],
        ),
    ]
