# Generated by Django 5.1.4 on 2025-01-18 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_personnelpompier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fireincident',
            name='email',
        ),
        migrations.RemoveField(
            model_name='fireincident',
            name='fire_description',
        ),
        migrations.RemoveField(
            model_name='fireincident',
            name='nearby_landmark',
        ),
    ]
